### ISSUE TITLE
href not working properly

### ISSUE THREAD

**Issue by SilversApprentice** [PigeonScript/PigeonScript.github.io#2]
@Sigton please help :P the href clearly says `"/index"`, and yet it always goes to `/index.html`. why is this?

**Comment by SilversApprentice** [comment]
nvm, it's just being stupid

**Comment by SilversApprentice** [comment]
well idk i'll leave this open

**Comment by SilversApprentice** [comment]
actually pretty much nothing's working right

**Comment by Sigton** [comment]
Just use /, or /<dirname>. You don't need to include the index, because a browser will always look for index.html implicitly.

Sigton

**Comment by SilversApprentice** [comment]
Ah, okay. Thanks :P

**Comment by Sigton** [comment]
No prob, happy to help :)

Sigton
